// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBridge_WEBAPI.Models;

namespace ShopBridge_WEBAPI.Migrations
{
    [DbContext(typeof(ShopBridgeDBContext))]
    partial class ShopBridgeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopBridge_WEBAPI.Models.Inventory", b =>
                {
                    b.Property<int>("item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("itemAvailability")
                        .HasColumnType("bit");

                    b.Property<DateTime>("item_AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("item_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("item_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("item_Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("item_Price")
                        .HasColumnType("float");

                    b.Property<int>("item_Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("item_UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("item_Id");

                    b.ToTable("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
